apiVersion: v1
kind: PersistentVolume
metadata:
  name: senzing-persistent-volume
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: ${NFS_PATH}
    server: ${NFS_SERVER}
  persistentVolumeReclaimPolicy: Retain
