apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: rabbitmq
    chart: rabbitmq-6.4.3
    heritage: Tiller
    release: my-rabbitmq
  name: myrabbitmq
  namespace: ${DEMO_NAMESPACE}
spec:
  host: myrabbitmq
  port:
    targetPort: stats
  to:
    kind: Service
    name: my-rabbitmq
    weight: 100
  wildcardPolicy: None
