image:
  registry: ${DOCKER_REGISTRY_URL}

imagePullSecrets:
  - name: ${DOCKER_REGISTRY_SECRET}

ingress:
  enabled: true
  hosts:
    - host: senzing-configurator.local
      paths:
        - /

senzing:
  databaseUrl: "${SENZING_DATABASE_URL}"
  persistentVolumeClaim: senzing-persistent-volume-claim
  subcommand: service
